### ISSUE TITLE
Replace input of other microphone-using apps

### ISSUE THREAD

**Issue by TheoTrig** [jurihock/voicesmith#13]
Is there a way to replace the normal microphone input of say Skype or normal phone calls with Voicesmith's altered output? Is there another use for voicesmith or is it simply to test if doing this on the Android 0S is possible?

**Comment by jurihock** [comment]
This issue is related to the legacy version of this app, which is no longer maintained.

The new version of the app uses the Oboe API. This should allow flexible routing.

However, I do not think that such a feature is feasible...
