### ISSUE TITLE
problems with DAF

### ISSUE THREAD

**Issue by Epixoft** [jurihock/voicesmith#14]
Hi Juri, I am trying to use your codebase to add more features into it. Your AAF portion works best for me but DAF has no slider and looking at the source code seems that DAF is not integrated. Can you tell me how DAF can be made to work in your code? with a slider to change delay from 20 upto 400 or 500 ms. Also, using another library I found that there is an inherent delay based on devices when we try to delay audio ourselves. But that thing does not happen when we only try to change the pitch by semitones. Can you shed some light on it please ?

I also need to record the unprocessed audio into audio files. Perhaps you can give me a hint on where to hook my code to get the unprocessed audio frames so I could write them into audio files. Just so you know, I am an iOS / Android developer and have created a similar AAF/DAF App for iOS using Core Audio prior to attempting it on Android using your code as well as another couple of libraries.

**Comment by karimabdelhameed** [comment]
any updates regarding this point

**Comment by jurihock** [comment]
This issue is related to the legacy version of this app, which is no longer maintained.

The new version of this app provides a configurable delay stage.
