### ISSUE TITLE
UnsatisfiedLinkError

### ISSUE THREAD

**Issue by meksin** [jurihock/voicesmith#15]
Hi, 
  when i click on the green button, the app stops and the log says: UnsatisfiedLinkError : 
Native method not found : de.jurihock.voicesmith.dsp.Math.pow:(FF) . Can you please suggest something. Thanks

**Comment by tarmin-rehve** [comment]
in case you're still interested for a fix, https://github.com/tarmin-rehve/voicesmith/pull/1 should solve this

**Comment by jurihock** [comment]
This issue is related to the legacy version of this app, which is no longer maintained.

The new version of the app includes a CI/CD build workflow on GitHub.
