### ISSUE TITLE
I build up everything NDK, and other files but gives error Native method not found

### ISSUE THREAD

**Issue by senkok** [jurihock/voicesmith#17]
java.lang.UnsatisfiedLinkError: Native method not found: de.jurihock.voicesmith.dsp.Math.abs:(FF)F
at de.jurihock.voicesmith.dsp.Math.abs(Native Method)

**Comment by tarmin-rehve** [comment]
in case you're still interested for a fix, https://github.com/tarmin-rehve/voicesmith/pull/1 should solve this

**Comment by tarmin-rehve** [comment]
in case you're still interested for a fix, https://github.com/tarmin-rehve/voicesmith/pull/1 should solve this

**Comment by jurihock** [comment]
This issue is related to the legacy version of this app, which is no longer maintained.

The new version of the app includes a CI/CD build workflow on GitHub.
