### ISSUE TITLE
how can i use for different voices

### ISSUE THREAD

**Issue by anil03** [jurihock/voicesmith#19]
Hi
i want to build anroid app which will record a sound. After recording a sound i want ti change that voice into ROBOT, Drunken voice, Female Voice, Alien voice like this.
it that possiible using your Example.
Please let me know how can i change the Frequency for each so that i can able to save the converted sounds.

**Comment by jurihock** [comment]
Thi one is an excellent lecture on digital audio effects:

https://dafx.de/DAFX_Book_Page_2nd_edition/index.html
