### ISSUE TITLE
Greendroid Issues

### ISSUE THREAD

**Issue by joem5636** [jurihock/voicesmith#20]
Greendroid compilation reports many errors with getActionBar() not returning a compatible object.  I suspect that Greendroid can be removed or is there a fix?

**Comment by tarmin-rehve** [comment]
In case you would still be interested with a fix, https://github.com/tarmin-rehve/GreenDroid/tree/v4.0.0 should solve the issue

**Comment by jurihock** [comment]
This issue is related to the legacy version of this app, which is no longer maintained.
