### ISSUE TITLE
Anyone figure out how to get this running in Android Studio? Eclipse seems dead...

### ISSUE THREAD

**Issue by billy8119** [jurihock/voicesmith#23]
well, it's all in the title.  A.S. Is choking on GreenDroid.  Halp?

**Comment by tarmin-rehve** [comment]
Hi @billy8119,

 You may want to take a look at this [fork](https://github.com/tarmin-rehve/voicesmith) which enable project build with android studio

**Comment by VeraUvads** [comment]
@tarmin-rehve I tried to use your fork, but it also doesn't work for me
<img width="424" alt="Screen Shot 2022-11-08 at 18 47 49" src="https://user-images.githubusercontent.com/57340969/200611220-8df6fc3e-fbec-4a62-9010-8d12cb924c13.png">

**Comment by tarmin-rehve** [comment]
Hi @VeraUvads ,
I've just had a try with a fresh cloned repo and it looks good to me with Android Studio 4.2.2.

- `git clone https://github.com/tarmin-rehve/voicesmith.git`
- `cd voicesmith`
- `git submodule update --recursive --init`

`git submodule update` is mandatory to fetch dependent submodules.

After getting all the source code, I simply started AS and selected the **inner** directory `voicesmith` as root of the projet:

![image](https://user-images.githubusercontent.com/85036844/201319273-4fd02682-90e2-4df8-924a-6090c58de7d1.png)

Then AS opened successfully the project:

![image](https://user-images.githubusercontent.com/85036844/201319734-53917bf1-3fae-40d2-85b8-5b6ee98121a4.png)

please, let me know if you're still under trouble.

**Comment by VeraUvads** [comment]
Had a problem with CMaker version.

Please tell me how did you solve this problem?
<img width="1675" alt="Screen Shot 2022-11-14 at 11 37 11" src="https://user-images.githubusercontent.com/57340969/201613586-18b8149d-20f1-4280-92b0-8e1165e15906.png">

**Comment by tarmin-rehve** [comment]
hello @VeraUvads ,

I'm a bit surprised by the issue that you report. Indeed MathDef.h includes **\<math.h>** not **\<cmath>**.
Did you change anything in the source code ?

**Comment by jurihock** [comment]
This issue is related to the legacy version of this app, which is no longer maintained.

The new version of the app is compatible with recent Android Studio and also includes a CI/CD build workflow on GitHub.
